# Utilizamos una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código al contenedor
COPY plotter.py /app/plotter.py

# Instalar las dependencias necesarias
RUN apt-get update && apt-get install -y inotify-tools && pip install --no-cache-dir matplotlib inotify
# Montar el volumen compartido
VOLUME ["/shared_volume"]

# Comando para ejecutar el plotter
CMD ["python", "plotter.py"]
