# Utilizamos una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código al contenedor
COPY server.py /app/server.py

# Instalar las dependencias necesarias
RUN pip install --no-cache-dir numpy scipy matplotlib

# Montar el volumen compartido
VOLUME ["/shared_volume"]

# Comando para ejecutar el servidor
CMD ["python", "server.py"]
